update dependencies Grunt and Bootstrap - set active class…
morganfeeney/bootstrap-patterns pull request #2
Opened 2017-05-01 11:16 UTC by atelierbram

In this PR I updated the dependencies for Grunt, and others as well in `package.json` because after NPM first install running the `grunt` command Grunt wouldn't run and generates an error. Bootstraps navbar needed some additional (updated) markup too with the new version.

I opted for setting an active class on the nav's list-items (like in Bootstrap) ISO on the link _in the templates_ ISO in javaScript. Using the [comparison](https://mozilla.github.io/nunjucks/templating.html#comparisons) operator `==`  here within an if-statement. This works when the values of the two variables `page_id` (in this example from `html/templates/page1.html`) and  `menu_item` from the for-loop in `html/components/nav.njk` _match_, ... and because of the way these templates render:

> Because assignments outside of blocks in child templates are global and executed before the layout template is evaluated it’s possible to define the active menu item in the child template:

In `html/templates/page1.html`:
```nunjucks
{% set page_id = "Page 1" %}   
```

In `html/components/nav.njk`:
```nunjucks
  <li class="nav-item {% if page_id == item.menu_item %}active{% endif %}">
```

2017-05-02 12:35 UTC, morganfeeney commented on package.json
> +    "url": "git+https://github.com/morganfeeney/bootstrap-patterns.git"
I haven't seen this before `+git`, what does it do?

2017-05-02 14:32 UTC, atelierbram commented on package.json
> +    "url": "git+https://github.com/morganfeeney/bootstrap-patterns.git"
Sorry I don't know, copy & paste thing from other repo. I will remove it in a bit.

2017-05-08 17:34 UTC, morganfeeney requested changes
Hi, i've spent a bit of time looking at the changes, I spotted a few things, if you don't have time just let me know and I'll pick them up ;)

There are a few outdated utility spacing classes used in the header that need to be updated, see example:
![image](https://cloud.githubusercontent.com/assets/1900222/25816594/78f7f5ec-341c-11e7-8ce7-3dc7745ea3f3.png)

You can see the same alignment issue in the footer too.

I notice in the nav, the word navbar is out of alignment with the content:

![image](https://cloud.githubusercontent.com/assets/1900222/25816783/204b0d0c-341d-11e7-8e0c-6ed6214a1803.png)

Any idea why?

2017-05-08 17:34 UTC, morganfeeney commented on src/html/partials/footer-scripts.njk
> +  // var url = window.location;
I see the point to this, I originally wanted some dynamic way to do this which is why I opted for the JS at that time. For example if the name of the file changes then you might have to also change the page id etc. 

However... from a learning point of view I think it's far better to show people how to add an active class using Nunjucks 👍.

@atelierbram You can go ahead and remove the JS rather than comment it out, ok?

2017-05-08 17:55 UTC, atelierbram commented
Morgan,

Next couple of days I don't have much time, maybe I can make some time on
thursday to do this right. I'm not deeply invested in Bootstrap, and the
repo is using an alpha version for the next release of Bootstrap, so I
don't know ... Personally I wouldn't mind waiting for the official release
of Bootstrap 4 to fix those outdated classes, for there might be more that
needs to be changed with that release.

​kind regards
,

Bram de Haan

***   ***   ***   ***   ***   ***   ***   ***   ***

2017-05-08 19:34 GMT+02:00 Morgan Feeney <notifications@github.com>:

> *@morganfeeney* requested changes on this pull request.
>
> Hi, i've spent a bit of time looking at the changes, I spotted a few
> things, if you don't have time just let me know and I'll pick them up ;)
>
> There are a few outdated utility spacing classes used in the header that
> need to be updated, see example:
> [image: image]
> <https://cloud.githubusercontent.com/assets/1900222/25816594/78f7f5ec-341c-11e7-8ce7-3dc7745ea3f3.png>
>
> You can see the same alignment issue in the footer too.
> ------------------------------
>
> In src/html/partials/footer-scripts.njk
> <https://github.com/morganfeeney/bootstrap-patterns/pull/2#discussion_r114308050>
> :
>
> > @@ -3,12 +3,12 @@
>  <script type="text/javascript" src="../node_modules/bootstrap/dist/js/bootstrap.js"></script>
>  <script src="http://localhost:35729/livereload.js"></script>
>  <script type="text/javascript">
> -  var url = window.location;
> +  // var url = window.location;
>
> I see the point to this, I originally wanted some dynamic way to do this
> which is why I opted for the JS at that time. For example if the name of
> the file changes then you might have to also change the page id etc.
>
> However... from a learning point of view I think it's far better to show
> people how to add an active class using Nunjucks 👍.
>
> @atelierbram <https://github.com/atelierbram> You can go ahead and remove
> the JS rather than comment it out, ok?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/morganfeeney/bootstrap-patterns/pull/2#pullrequestreview-35761900>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAz3ibYsjdA_MhvFVYLykezmxsWJJ-xqks5r31IJgaJpZM4NM-zt>
> .
>

2017-05-09 07:35 UTC, morganfeeney commented
I'm gonna merge this in, and fix the classes myself. If BS updates then... well it's not exactly a big job to correct. Thanks for the effort.

2017-05-09 07:36 UTC, merged

2017-05-09 08:26 UTC, atelierbram commented
Great - thanks; you're welcome